Collab/Models/Notebook.cs
using System;
using System.Collections.Generic;

namespace Collab.Models;

public partial class Notebook
{
    public int NotebookId { get; set; }

    public string? NotebookTitle { get; set; }

    public DateTime? NotebooAddDate { get; set; }

    public string? NotebookContent { get; set; }

    public int? ProgramId { get; set; }

    public int? MemberId { get; set; }

    public virtual Member? Member { get; set; }

    public virtual Program? Program { get; set; }
}

Collab/Controllers/NoteAddController.cs
using Collab.Filters;
using Collab.Models;
using Microsoft.AspNetCore.Mvc;

namespace Collab.Controllers
{
    public class NoteAddController : Controller
    {
        private readonly TestBananaContext _bananaContext;

        public NoteAddController(TestBananaContext bananaContext)
        {
            _bananaContext = bananaContext;
        }

        [ServiceFilter(typeof(ProfilePicturePathFilter))]
        public IActionResult Index()
        {
            return View();
        }

        [ServiceFilter(typeof(ProfilePicturePathFilter))]
        [HttpPost]
        public IActionResult Index(string TitleAdd, string ContentAdd)
        {
            string programIdStr = Request.Cookies["ProgramId"];
            int.TryParse(programIdStr, out int programId);
            string userIdStr = Request.Cookies["UserID"];  // 從 Session 或 Cookie 中獲取當前登錄會員的 ID
            int.TryParse(userIdStr, out int userId);

            var AddNB = new Notebook
            {
                NotebookTitle = TitleAdd,
                NotebookContent = ContentAdd,
                NotebooAddDate = DateTime.Now,
                ProgramId = programId,
                MemberId = userId
            };

            var NotifyAdd = new Notify
            {
                NotifyDate = DateTime.Now,
                NotifyAction = "新增",
                NotifyType = "記事本",
                ActionName = TitleAdd,
                ProgramId = programId,
                MemberId = userId                
            };
            _bananaContext.Notebooks.Add(AddNB);
            _bananaContext.Notifies.Add(NotifyAdd);
            _bananaContext.SaveChanges();
            return RedirectToAction("Index","Notebook");
        }
    }
}

Collab/Controllers/NotebookController.cs
using Collab.Models;
using Microsoft.AspNetCore.Mvc;
using Collab.Filters;

namespace collab_00.Controllers {
    public class NotebookController : Controller {

        private readonly TestBananaContext _bananaContext;

        public NotebookController(TestBananaContext bananaContext)
        {
            _bananaContext = bananaContext;
        }
        [ServiceFilter(typeof(ProfilePicturePathFilter))]
        public IActionResult Index(int? SortNum) {

            string programIdStr = Request.Cookies["ProgramId"];
            int.TryParse(programIdStr, out int programId);
            

            var NB_Bag = from Howhow in _bananaContext.Notebooks
                         join Diedie in _bananaContext.Members on Howhow.MemberId equals Diedie.MemberId
                         where Howhow.ProgramId == programId
                         select new TestBananaContext
                         {
                             NBT = Howhow.NotebookTitle,
                             NBCT = Howhow.NotebooAddDate.ToString(),
                             NBImg = Diedie.MemberPhoto
                         };
            switch (SortNum)
            {
                case 1:
                    NB_Bag = NB_Bag.OrderByDescending(x => x.NBCT);
                    break;

                case 2:
                    NB_Bag = NB_Bag.OrderBy(x => x.NBCT);
                    break;

                default:
                    break;
            }
            //if (SerchWd != null)
            //{
            //    NB_Bag = NB_Bag.Where(item => item.NBT.Contains(SerchWd));
            //}
            return View(NB_Bag.ToList());
        }

        [ServiceFilter(typeof(ProfilePicturePathFilter))]
        [HttpPost]
        public IActionResult Index(string SerchWd)
        {

            string programIdStr = Request.Cookies["ProgramId"];
            int.TryParse(programIdStr, out int programId);
            
            if (SerchWd == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                var NB_Bag = from Howhow in _bananaContext.Notebooks
                             join Diedie in _bananaContext.Members on Howhow.MemberId equals Diedie.MemberId
                             where Howhow.ProgramId == programId && Howhow.NotebookTitle.Contains(SerchWd)
                             select new TestBananaContext
                             {
                                 NBT = Howhow.NotebookTitle,
                                 NBCT = Howhow.NotebooAddDate.ToString(),
                                 NBImg = Diedie.MemberPhoto
                             };

                ViewBag.SrWd = SerchWd;
                return View(NB_Bag.ToList());
            }

        }
    }
}

Collab/Views/Notebook/Index.cshtml
@model List<TestBananaContext>

<link rel="stylesheet" href="~/css/Notebook.css" />


<div class="container">
    <div class="mb-4">
        <div class="row mx-2">
            <!-- <div class="col-sm-5 mt-5">
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="搜尋標題"
                        aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </form>
            </div> -->
            @*搜尋框框*@
            <div class="col-sm-5 mt-5">

                <form id="searchForm" asp-action="Index" asp-controller="Notebook" method="post">
                    <input class="searchInput" type="text" placeholder="搜尋標題" name="SerchWd" value=@ViewBag.SrWd onfocus="this.placeholder = ''" onblur="this.placeholder = '搜尋標題'">
                    <a class="icon-search" onclick="submitForm()"><i class="fa-solid fa-magnifying-glass fa-2xl"></i></a>
                </form>

                <script>
                    function submitForm() {
                        document.getElementById("searchForm").submit();
                    }
                </script>
            </div>
            @*搜尋框框*@

            <div class="col-sm-7 mt-5">
            </div>
            <div class="col-sm-9 mt-5">
                <a href="@Url.Action("Index","NoteAdd")" class="addNote">
                    <i class="fa-regular fa-square-plus fa-2xl" style="font-size: 40px;"></i>
                    <span>新增記事本</span>
                </a>
            </div>

            <div class="col-sm-3 mt-5">
                <div class="sort">
                    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton1"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        排序方式
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="@Url.Action("Index",new {SortNum = 1})">日期由近到遠</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Index",new {SortNum = 2})">日期由遠到近</a></li>
                    </ul>
                </div>

            </div>
            <!-- 以下區塊為記事本條列 -->

            <div class="col-sm-12 mt-4 custom-div">

                @foreach (var i in Model)
                {
                    <div class="row justify-content-center">
                        @*記得href後面的href要用雙引號包好==*@
                        @*<a href="@Url.Action("NoteBookEdit", new { NBTitle = i.NBT }) class="col-md-12 mt-3">*@
                        <a href="@Url.Action("Index","NoteEdit", new { NBTitle = i.NBT })" class="col-md-12 mt-3">
                            <div class="NbListInside  p-4 my-1">
                                <div class="d-flex align-items-center" style="height: 100%;">
                                    <!-- 區塊的內容 -->
                                    <div class="col-sm-4">
                                        <p class="CtrNbIfo">@i.NBT</p>
                                    </div>
                                    <div class="col-3"></div>
                                    <div class="col-sm-3">
                                        <p class="CtrTimeBox">@i.NBCT</p>
                                    </div>
                                    <div class="col-1"></div>
                                    <div class="col-sm-1">
                                        <div class="NbListCtr">
                                            <img src=@i.NBImg>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>


    <script>
        // // 获取当前日期
        // var today = new Date();

        // // 将日期格式化为字符串
        // var dateString = today.toLocaleDateString();

        // // 将日期字符串显示在指定的区块内
        // document.getElementById("dateBlock").textContent = dateString;

        document.getElementById('AddNotebook').addEventListener('click', function () {
            window.open('./LayoutTestEdit.html', '_blank');
        });

    </script>

    <!--------功能內頁END------>
</div>

@*<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ"
        crossorigin="anonymous"></script>*@